### ISSUE TITLE
about snap.disable()

### ISSUE THREAD

**Issue by whushiny** [liubgithub/maptalks.snapto#1]
创建一个mode为point的snaptool添加至点图层，用于画点后在点的基础上连线构面，但在连线构面模式之外，并不希望出现有snaptool的蓝色圆点，尝试使用disable()方法关闭snaptool，但蓝色圆点并未消失

**Comment by liubgithub** [comment]
好的，等会我看看

**Comment by liubgithub** [comment]
那个问题我修复了，你npm update maptalks.snapto一下再看看

**Comment by whushiny** [comment]
现在的disable()是彻底移除了snaptool么，disable之后再enable好像snaptool没有办法再继续出现了

**Comment by liubgithub** [comment]
哦，收到，我忘了测试这个功能，我改一下

**Comment by liubgithub** [comment]
好了，那个bug我修复了，你再试一下吧

**Comment by whushiny** [comment]
好的，目前没问题了~
