### ISSUE TITLE
snap to Circle/Ellipse/Rectangle

### ISSUE THREAD

**Issue by fuzhenn** [liubgithub/maptalks.snapto#2]
mode为Point时，粘着点都在图形的中心点（矩形在右上角），应该改为黏着在端点上

Circle/Ellipse/Rectangle可以用getShell()来获取端点坐标

**Comment by liubgithub** [comment]
这个中心点是画的时候，因为设置了符号marker，效果确实是粘在端点上的

**Comment by fuzhenn** [comment]
好的，请丰富一下demo，把功能在demo里详细展示出来

**Comment by fuzhenn** [comment]
哦， 对了， demo地图别用现在的底图了，可以换成免费的carto dark之类的在线底图
https://github.com/maptalks/raster-collection

**Comment by liubgithub** [comment]
好的，我刚自己测了一下，还有一个bug，改一下
