### ISSUE TITLE
improve demos

### ISSUE THREAD

**Issue by fuzhenn** [liubgithub/maptalks.snapto#4]
目前一些用户反应snapto的功能demo不全，不清楚怎么使用，请完善一下snapto的demo
示例1：添加一批线，面数据，演示自动吸附到线/面上（line mode）
示例2：添加一批点，线，面数据，演示自动吸附到它们的端点上 （Point mode）
示例3：drawTool的吸附

**Comment by liubgithub** [comment]
好的，这几天比较忙，可能我写的还是不够直观，稍后我会完善一下
