### ISSUE TITLE
能否请求增加对Circle对象圆心吸附的功能呢？

### ISSUE THREAD

**Issue by DragonEmperorG** [liubgithub/maptalks.snapto#5]
如果我想pull request的话得看哪一部分的代码，或者得理解这整个工具是怎么运作的吗？

**Comment by liubgithub** [comment]
目前是可以吸附Circle对象的圆心的，先画一个圆，再把snapto的模式换成point模式，你看一下demo，https://liubgithub.github.io/archives/demo/

**Comment by liubgithub** [comment]
如果还有什么问题，可以加我qq471071362,我帮你看看
