### ISSUE TITLE
吸附DT图层在JZD图层画点，画完点后吸附的图层自动变成了JZD图层

### ISSUE THREAD

**Issue by whushiny** [liubgithub/maptalks.snapto#6]
http://jsfiddle.net/uhon5Lhs/94/
提供了DT和JZD两个图层，要求吸附DT图层上的点在JZD图层上绘制点。
1、点击toolbar上的drawpoi按钮后，点击snapto按钮，选择DT，吸附DT图层绘制两到三个点，吸附图层未发生改变，无任何问题；
2、点击snapto按钮，选择JZD，设置吸附图层为JZD图层，再次点击snapto按钮，选择DT，切换回吸附DT图层；
3、进行吸附DT图层绘制JZD的操作，当绘制完一个点后，发现吸附的图层变为了JZD图层

**Comment by liubgithub** [comment]
收到，谢谢！
我晚点来看一下

**Comment by liubgithub** [comment]
你好，已经修复了这个问题，你可以npm update一下
